### ISSUE TITLE
Enhancement: Update images used in gh actions upon merging to main

### ISSUE THREAD

**Issue by zachmandeville** [kubernetes-sigs/apisnoop#590]
There are at least two references to snoopdb within this repo that do not necessarily match the canonical, up-to-date version of snoopdb.

1.) our helm charts, which is used whenever someone starts up snoop on a pair instance
2.) our updater gh action, which is used to update the coverage jsons in the repo and the website.

Whenever there is a new push to main, we build a new image of snoopdb. We then have to remember to manually update both of these files.  If that is forgotten, it can cause unintuitive errors, where the code you are investigating in the repo does not match the code referenced in the error--since the instance may be using an image of snoopdb from several months ago.

It would be great to have, as part of a ci, a way to update these files so they are always using the latest image of snoopdb.  If something is committed to main, than we must know that it is going to affect all our versions of snoop.  I think it would be good to build in checks for updates rather than having to manually adjust all these files.

**Comment by BobyMCbobs** [comment]
This is a great idea.

It would be triggered if on the main branch and run something similar to 
```
LATEST_IMAGE="$(gcrane ls gcr.io/k8s-staging-apisnoop/snoopdb | sort -ur | head -n 1)"
LATEST_TAG="$(echo "$LATEST_IMAGE" | cut -d ':' -f2)"
find . -not -path ".git" -type f -exec sed -i "s,gcr.io/k8s-staging-apisnoop/snoopdb:v.*,$LATEST_IMAGE,g" {} \;
find . -not -path ".git" -type f -exec sed -i "s,appVersion: v.*,appVersion: $LATEST_TAG,g" {} \;
```

then committing and submitting a PR if there are changes

**Comment by hh** [comment]
There is a similar pattern used within #sig-testing to update the release of prow images:

https://github.com/kubernetes/test-infra/blob/734af3df12ca4bbcd63ee09955f464433b9fdbe0/config/prow/autobump-config/prow-job-autobump-config.yaml

resulting in PRs like:

https://github.com/kubernetes/test-infra/commit/ca715580379d2d988a4b09b7c9c327995279e266

**Comment by hh** [comment]
Underlying go code https://github.com/kubernetes/test-infra/tree/799656f1600a4cc5d2ee8d41487365913aaf3622/prow/cmd/generic-autobumper#autobumper
