### ISSUE TITLE
Add a Github action to identify Conformance test that was promoted without meta data

### ISSUE THREAD

**Issue by Riaankl** [kubernetes-sigs/apisnoop#796]
Graduate APIListChunking to GA [#119503](https://github.com/kubernetes/kubernetes/pull/119503/) added two conformance tests without meta data.
```
~/go/src/k8s.io/kubernetes$ hack/update-conformance-yaml.sh
 
go version go1.21.1 linux/amd64
+++ [0911 09:29:42] Building go targets for linux/amd64
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
    k8s.io/kubernetes/test/e2e/e2e.test (test)
2023/09/11 09:30:02 Did not find test info for spec: "[sig-api-machinery] Servers with support for API chunking should return chunks of results for list calls [Conformance]"
2023/09/11 09:30:02 Did not find test info for spec: "[sig-api-machinery] Servers with support for API chunking should support continue listing from the last key if the original version has been compacted away, though the list is inconsistent [Slow] [Conformance]" 
```
Create a Github action that run [`hack/update-conformance-yaml.sh`](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#promoting-tests-to-conformance) reporting all instances of "Did not find test info for spec:" in a Issue in the Kubernetes/Kubernetes repo with the labels:
```
/sig testing
/sig architecture
/area conformance
```

**Comment by BobyMCbobs** [comment]
Perhaps the more optimal way might be to create a merge blocking job in kubernetes/test-infra for when test/e2e or test/conformance have been edited to run `hack/update-conformance-yaml.sh` and if there's difference then fail

**Comment by Riaankl** [comment]
Like this approach more. Please start working on it. @BobyMCbobs

**Comment by BobyMCbobs** [comment]
@Riaankl, I added a ticket (https://github.com/kubernetes/test-infra/issues/30770) and PR (https://github.com/kubernetes/test-infra/pull/30771) to add the feature. It may need some tweaking. I haven't tested it yet since I don't have an environment setup just yet but I'll be getting around to it.

**Comment by BobyMCbobs** [comment]
Potential flakes?

https://github.com/kubernetes/test-infra/pull/30771#issuecomment-1727202900

**Comment by BobyMCbobs** [comment]
Trying to progress with this with

```shell
./config/mkpj.sh --job=pull-kubernetes-conformance-yaml -pull-number=30771 > /tmp/pj.yaml
go run ./prow/cmd/mkpod/main.go -prow-job /tmp/pj.yaml > /tmp/pj-pod.yaml
```

then tinkering with some values to get it to run
