### ISSUE TITLE
Endpoint createCoreV1NamespacedServiceAccountToken shows up as not tested

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes-sigs/apisnoop#914]
The test for ServiceAccount TokenReview was merged then once ready promoted
https://github.com/kubernetes/kubernetes/pull/127943

Unfortunately, the data does not appear to reflect the actual state
https://apisnoop.cncf.io/conformance-progress/endpoints/1.32.0/?filter=untested

The issue may reside in one or more of the following places
- conformance test job data
- APISnoop coverage data generation
- ProwJob test runs

According to testgrid and Prow, it appears to be running the test
- https://testgrid.k8s.io/sig-arch-conformance#kind-conformance-audit&include-filter-by-regex=should%20create%20a%20serviceAccountToken%20and%20ensure%20a%20successful%20TokenReview
- https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-audit-kind-conformance/1863280199324405760

**Comment by BobyMCbobs** [comment]
It appears that the test was skipped

<img width="1341" alt="Screenshot 2024-12-02 at 10 40 06" src="https://github.com/user-attachments/assets/fe057809-4ed8-4217-802f-a13fe24e9e79">

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-audit-kind-conformance/1844823362518388736/artifacts/junit_01.xml

**Comment by BobyMCbobs** [comment]
Job declaration, see YAML
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-audit-kind-conformance/1844823362518388736

**Comment by heyste** [comment]
Testing the [e2e test](https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/test/e2e/auth/service_accounts.go#L871-L878) locally does produce the required `[Conformance]` label but the prow job doesn't.

```
[sig-auth] ServiceAccounts should create a serviceAccountToken and ensure a successful TokenReview [Conformance] [sig-auth, Conformance]
/home/ii/go/src/k8s.io/kubernetes/test/e2e/auth/service_accounts.go:878
  STEP: Creating a kubernetes client @ 12/02/24 03:41:17.271
  I1202 03:41:17.271844 208403 util.go:502] >>> kubeConfig: /home/ii/.kube/config
  STEP: Building a namespace api object, basename svcaccounts @ 12/02/24 03:41:17.272
  STEP: Waiting for a default service account to be provisioned in namespace @ 12/02/24 03:41:17.291
  STEP: Waiting for kube-root-ca.crt to be provisioned in namespace @ 12/02/24 03:41:17.294
  STEP: Creating a Serviceaccount "e2e-sa-j8rhm" in namespace "svcaccounts-7654" @ 12/02/24 03:41:17.296
  STEP: Creating a ServiceaccountToken "e2e-sa-j8rhm" in namespace "svcaccounts-7654" @ 12/02/24 03:41:17.299
  STEP: Creating a TokenReview for "e2e-sa-j8rhm" in namespace "svcaccounts-7654" @ 12/02/24 03:41:17.302
  I1202 03:41:17.306168 208403 helper.go:124] Waiting up to 7m0s for all (but 0) nodes to be ready
  STEP: Destroying namespace "svcaccounts-7654" for this suite. @ 12/02/24 03:41:17.308
• [0.046 seconds]
```

**Comment by BobyMCbobs** [comment]
This now appears to be resolved. @heyste, would you please confirm?
https://apisnoop.cncf.io/conformance-progress/endpoints/1.32.0/?filter=untested

**Comment by heyste** [comment]
The issue has been resolved.
